{
  "comments": [
    {
      "key": {
        "uuid": "4b16ab4d_91df0bff",
        "filename": "include/sdbusplus/unpack_properties.hpp",
        "patchSetId": 3
      },
      "lineNbr": 160,
      "author": {
        "id": 1000000
      },
      "writtenOn": "2021-10-21T16:16:38Z",
      "side": 1,
      "message": "Add `noexcept`",
      "revId": "d69854e35eb26383f082fa531efbc3afb61e5670",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "483e42ee_61d46e3d",
        "filename": "include/sdbusplus/unpack_properties.hpp",
        "patchSetId": 3
      },
      "lineNbr": 160,
      "author": {
        "id": 1001026
      },
      "writtenOn": "2021-10-21T19:31:40Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "4b16ab4d_91df0bff",
      "revId": "d69854e35eb26383f082fa531efbc3afb61e5670",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "10c9b590_a759923f",
        "filename": "include/sdbusplus/unpack_properties.hpp",
        "patchSetId": 3
      },
      "lineNbr": 165,
      "author": {
        "id": 1000000
      },
      "writtenOn": "2021-10-21T16:16:38Z",
      "side": 1,
      "message": "I don\u0027t understand how this turns the function into a non-throwing.  The \u0027common\u0027 function still throws and there is no catch here.",
      "range": {
        "startLine": 163,
        "startChar": 0,
        "endLine": 165,
        "endChar": 41
      },
      "revId": "d69854e35eb26383f082fa531efbc3afb61e5670",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "0adcd2d7_f6d09ef5",
        "filename": "include/sdbusplus/unpack_properties.hpp",
        "patchSetId": 3
      },
      "lineNbr": 165,
      "author": {
        "id": 1001026
      },
      "writtenOn": "2021-10-21T19:31:40Z",
      "side": 1,
      "message": "By passing badProperty, we are certain that condition in line 123 is always false, and there is the only throwing block in the common function. So this means, there is no need to catch anything. Or am I wrong? I am open for other ideas, but my intention here was to not duplicate much code.",
      "parentUuid": "10c9b590_a759923f",
      "range": {
        "startLine": 163,
        "startChar": 0,
        "endLine": 165,
        "endChar": 41
      },
      "revId": "d69854e35eb26383f082fa531efbc3afb61e5670",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    }
  ]
}